# Configuration pour Railway
[build]
builder = "NIXPACKS"
buildCommand = "cd client && npm install && npm run build"

[build.environment]
NODE_VERSION = "18"
NPM_CONFIG_PRODUCTION = "false"
NPM_CONFIG_LEGACY_PEER_DEPS = "true"
NODE_ENV = "production"

[deploy]
startCommand = "cd client && npm start"
